; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Wed Jun 21 2017 10:31:25 GMT+0100 (BST)

; Clear any bed transform
M561

; Home all axes
G28

; Probe the bed at 5 points
G30 P0 X25 Y25 H0 Z-99999
G30 P1 X25 Y175 H0 Z-99999
G30 P2 X175 Y175 H0 Z-99999
G30 P3 X175 Y25 H0 Z-99999
G30 P4 X100 Y100 H0 Z-99999 S

