; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Sun Jul 02 2017 11:18:04 GMT+0100 (BST)

; Lift Z relatively to current position
G91
G1 Z40 F6000

; Move Z down until the switch triggers
G1 Z-185 S1 F360

; Back to absolute positioning
G90

; Tell the firmware where we are
G92 Z2.5

; Uncomment the following lines to lift Z after probing
;G91
;G1 Z5 F100
;G90
